# **Задание на повторение материала
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [135]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [136]:
a = a.reshape(2, 6)
print(a)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [137]:
b = a.reshape(1, 12)
b

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [138]:
c = a.reshape(12, 1)
c

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [139]:
d = a.reshape(6, 2)
d

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [140]:
e = a.reshape(3, 4)
print(e)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [141]:
a1 = a.reshape(1,-1)
a1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [142]:
b1 = a.reshape(2,-1)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [143]:
c1 = a.reshape(6,-1)
c1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [144]:
d1 = a.reshape(-12,1)
d1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [145]:
e1 = a.reshape(-1,3)
e1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [123]:
A = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
B = A.reshape (12,1)
print(A.ndim,  B.ndim)


1 2


Ответ: нет

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [32]:
m = np.random.randn(3, 4)
m.size
m

array([[ 0.49491996,  1.2123009 ,  1.3437021 , -0.45043692],
       [ 0.51767432, -1.88592127,  0.52625821,  0.39268546],
       [-1.21595304,  1.07232497, -1.87056782,  0.75426786]])

In [34]:
n = m.flatten()
n.size
m.size == n.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.

In [128]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?

In [129]:
b = np.arange(20, 0, -2)
b = b.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [130]:
np.array_equal(a, b) 

False

In [131]:
a.ndim, b.ndim 

(1, 2)

Ответ: разница в размерности массивов

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [43]:
a = np.zeros((2, 2))

b = np.ones((3, 2))

v = np.concatenate((a, b), axis=0)
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [90]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [47]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [49]:
# чтобы определить размер матрицы
B.size

16

In [50]:
np.linalg.det(B)

0.0

Вычислить обратную матрицу для B не получится, т.к. определитель матрицы B равен 0.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [52]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [103]:
c = np.random.randint(0, 16, 16)
c

array([13,  1,  9,  8,  9,  4,  1,  3, 11, 14, 11,  6, 11, 12,  7, 14])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [104]:
C = c.reshape((4, 4))
print(C)

[[13  1  9  8]
 [ 9  4  1  3]
 [11 14 11  6]
 [11 12  7 14]]


In [105]:
D = B + C * 10
D

array([[135,  24, 113, 112],
       [104,  90,  96, 152],
       [133, 226, 259, 272],
       [142, 242, 282, 442]])

In [106]:
op = np.linalg.det(D) # определитель
r = np.linalg.matrix_rank(D) # ранг
D_inv = np.linalg.inv(D)
print(op, r)
print(D_inv)

179559199.99999994 4
[[ 0.00161139  0.01573331 -0.00060337 -0.00544756]
 [-0.01171536  0.01616581  0.00587973 -0.00620898]
 [ 0.00970588 -0.02297749  0.00672035  0.00130676]
 [-0.00029584  0.00075429 -0.00731302  0.00657833]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [107]:
positive = D_inv > 0
negative = D_inv < 0
D_inv[positive] = 1
D_inv[negative] = 0
print(D_inv)

[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]]


In [108]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   9   8]
 [  9  50  86   3]
 [ 23  14 149 212]
 [ 11 122   7 302]]
